### ISSUE TITLE
Document and test example customisations

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#203]
This issue supersedes the following.

- [ ] #23 (Traefik 1.x) 
- [ ] #56 (PHPMyAdmin)
- [ ] #62 (Portainer)
- [ ] #63 (Cowsay)
- [ ] #66 (HTTPS)
- [ ] #67 (Custom images)
- [ ] #68 (Alternative domain)
- [ ] #85 (Non-standard Mailhog port)
- [ ] #151 (Replacement reverse proxy)
- [ ] #153 (Traefik 2.x)
- [ ] #177 (Custom ssh-agent)

The following need to be resolved before this issue can be closed:

- [ ] Documentation added for each example (above)
- [ ] CI Tests for each of them

**Comment by fubarhouse** [comment]
Details here: https://github.com/fubarhouse/pygmy-go/compare/issue/203?expand=1

**Comment by christopher-hopper** [comment]
Currently a search for Pygmy documentation lands you at https://pygmy.readthedocs.io/

To submit a change to that documentation, the site links you back to Github at https://github.com/amazeeio/pygmy/blob/master/docs/

Pull Requests to update documentation at the above repository are left un-answered, as it is now unmaintained in favour of pygmy-go (this repository).

I had a troubleshooting issue and wanted to add it to the documentation for pygmy, but there's not a clear way to do that. Where is the source for the documentation? Here in pygmy-go, or there in the old python pygmy?

Reference:
https://github.com/amazeeio/pygmy/pull/59

**Comment by tobybellwood** [comment]
yarr - it's still in a transition phase - ultimately the docs here will be the final ones, likely via gh-pages, or similar (and pygmy.readthedocs likely repointed here).  We won't merge PRs into the old pygmy, so documenting things in the README here makes sense for now.

We (the @uselagoon team) haven't been able to dedicate much time here in the last few weeks, but will aim to get this going again.
