### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#34]
We've copied the ruby docs for this POC - we should make a conservative effort to update it for  what comes out of the box (not custom configurations).

**Example configuration changes**
- [ ] #23 - `Traefik 1.x`
- [ ] #56 - `phpmyadmin`
- [ ] #62 - `Portainer`
- [ ] #63 - `Cowsay` (a Docker version of it)
- [ ] #66 - Run on https instead
- [ ] #67 - Image replacement
- [ ] #68 - Alternative domain integration
- [ ] #85 - Non-standard mailhog port
- [ ] #151 - Replacement reverse proxy (Now in CI)
- [ ] #153 - `Traefik 2.x` (Now in CI)

**Other requirements**
- [ ] Other

**Comment by fubarhouse** [comment]
Now limiting the scope to documentation _mostly_ what was previously provided.
A PR will be opened to close this issue and additional documentation will be added to a new issue.
